@echo off
mkdir build
cd build
cmake .. -G "Visual Studio 17 2022" -DUSE_SYSTEM_SDL2=ON -DALLOW_EXTERNAL_SPIRV_TOOLS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DENABLE_QT_TRANSLATION=ON -DCITRA_ENABLE_COMPATIBILITY_REPORTING=ON -DSDL2_LIBRARY="externals/sdl2/SDL2.lib" -DSDL2_INCLUDE_DIR="externals/sdl2/SDL/include" -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DUSE_DISCORD_PRESENCE=ON